meta_title: "Circolo Del Design"
meta_description: "Uno spazio aperto, inclusivo e partecipato. Narratore di storie, personaggi e imprese che hanno contribuito alla crescita dell mondo della cultura del progetto."
meta_image: "CircoloDelDesign_1200x630.png" # should exist in `app/assets/images/`
twitter_account: "@CdD_torino"   # required for Twitter Cards
