meta_title: "Circolo Del Design"
meta_description: "Al Circolo del Design le aziende incontrano i professionisti, i progettisti si confrontano e si danno appuntamento, i ricercatori e gli studenti consultano la biblioteca e trovano un luogo in cui studiare e lavorare."
meta_keywords: "Circolo Del Design, Circolo, Torino, Design"
meta_image: "CircoloDelDesign_1200x630.png" # should exist in `app/assets/images/`
twitter_account: "@CdD_torino" # required for Twitter Cards
