class Carousel < ApplicationRecord
  # extends ...................................................................

  # includes ..................................................................
  include Publishable
  
  # relationships .............................................................
  has_many :images, as: :imageable, dependent: :destroy

  # validations ...............................................................

  # callbacks .................................................................

  # scopes ....................................................................

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  accepts_nested_attributes_for :images, allow_destroy: true

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................

  # protected

  # private instance methods ..................................................

  # private
end
