class Page < ApplicationRecord
  # extends ...................................................................
  extend FriendlyId
  friendly_id :title, use: :slugged

  # includes ..................................................................
  mount_uploader :cover, ImageUploader
  
  # relationships .............................................................
  has_one :page_meta_datum, as: :metadatable, dependent: :destroy
  has_many :content_blocks, as: :contentable, dependent: :destroy

  # validations ...............................................................
  validates :title, :slug, presence: true
  validates :priority, :lang, numericality: { only_integer: true }

  # callbacks .................................................................

  # scopes ....................................................................

  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  accepts_nested_attributes_for :page_meta_datum, allow_destroy: true
  accepts_nested_attributes_for :content_blocks, allow_destroy: true

  # class methods .............................................................
  class << self
  end

  # public instance methods ...................................................

  # protected instance methods ................................................
  # protected

  # private instance methods ..................................................
  # private
end
